PREFIX gmont: <https://matinabtahi.github.io/Generational-MemoryOntology/GMOnt#>

SELECT DISTINCT ?entity ?record ?date ?media ?mediaType
WHERE {
  ?record (gmont:aboutEntity|gmont:aboutPerson|gmont:aboutOrganization|gmont:aboutPlace|gmont:aboutObject|gmont:aboutEvent) ?entity ; gmont:recordDate ?date ; gmont:hasMedia ?media .
  ?media gmont:mediaType ?mediaType .
}
ORDER BY ?entity ?date ?mediaType ?media
